### PR TITLE
chore(beacon): we are so back (and by back i mean decoupled and by we i mean the beacon and consensus-types module)

### PR DESCRIPTION
**Pull request by archbear**

### CODE REVIEW

**Comment by itsdevbear** [comment]
lgtm once fix whatever the issues are, I don't love the generic for Deneb, so let's fix it in a full up PR

**Comment by itsdevbear** [comment]
follow up**

**Review by ocnc2 — COMMENTED** [review]
we love decoupling

**Comment by ocnc2** [comment]
wen decouple

**Comment by archbear** [comment]
closed in favour of #1518

**Pull request closed without merging**
